apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microservice-a
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      containers:
        - name: microservice-a
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000