apiVersion: v1
kind: Service
metadata:
  name: microservice-a
spec:
  type: {{ .Values.service.type }}
  selector:
    app: microservice-a
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000